# Generated by Django 6.0.4 on 2026-05-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_cart_cartitem_wishlist_delete_carouselitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['added_at'], 'verbose_name': 'Savat mahsuloti', 'verbose_name_plural': 'Savat mahsulotlari'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefon raqami'),
        ),
    ]
