# Generated by Django 6.0.4 on 2026-06-09 14:03

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Product = apps.get_model("apps", "Product")
    seen = set()
    for product in Product.objects.all():
        base = slugify(product.title) or f"product-{product.pk}"
        slug = base
        n = 2
        while slug in seen or Product.objects.filter(slug=slug).exclude(pk=product.pk).exists():
            slug = f"{base}-{n}"
            n += 1
        product.slug = slug
        product.save(update_fields=["slug"])
        seen.add(slug)


class Migration(migrations.Migration):

    atomic = False  # needed: populate data between schema changes

    dependencies = [
        ("apps", "0004_alter_cartitem_options_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Faol"),
        ),
        # Step 1: add slug WITHOUT index or unique (db_index=False prevents _like index)
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.CharField(blank=True, max_length=300, default="", db_index=False),
            preserve_default=False,
        ),
        # Step 2: populate slugs for existing rows
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Step 3: convert to SlugField with unique (creates both key and _like indexes fresh)
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.CreateModel(
            name="ColorVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                ("hex_code", models.CharField(max_length=20, verbose_name="Hex kod")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_variants",
                        to="apps.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rang varianti",
                "verbose_name_plural": "Rang variantlari",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ColorVariantPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="products/colors/", verbose_name="Rasm"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="apps.colorvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rang rasmi",
                "verbose_name_plural": "Rang rasmlari",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StorageOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50, verbose_name="Yorliq")),
                ("storage", models.CharField(max_length=50, verbose_name="Xotira")),
                (
                    "ram",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="RAM"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="Narx"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_options",
                        to="apps.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xotira varianti",
                "verbose_name_plural": "Xotira variantlari",
                "ordering": ["order"],
            },
        ),
    ]
